version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - maintenance

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - ci
      - maintenance
