import { EyeOff, Heart } from "lucide-react";
import { adminCompleteWishAction, updateWishAdminMetaAction } from "@/app/actions";
import { getAdminWishesData } from "@/lib/life-data";
import { Card } from "@/components/ui/card";
import { Flash } from "@/components/ui/flash";
import { MediaImage } from "@/components/ui/media-image";
import { SubmitButton } from "@/components/ui/submit-button";

export default async function AdminWishesPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string }> }) {
  const [data, flash] = await Promise.all([getAdminWishesData(), searchParams]);
  return <div><div className="mb-5"><h2 className="text-xl font-black text-brown">愿望与秘密准备</h2><p className="mt-1 text-sm text-muted">秘密状态存放在独立表，普通用户没有读取权限。</p></div><Flash {...flash} /><div className="space-y-4">{data.wishes.length ? data.wishes.map((wish) => { const meta = data.meta.find((item) => item.wish_id === wish.id); return <Card key={wish.id}><div className="flex gap-4">{wish.signed_url && <MediaImage src={wish.signed_url} alt={wish.title} className="size-20 rounded-2xl" />}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Heart className="size-4 text-rose-500" /><h3 className="font-black text-brown">{wish.title}</h3><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-brown">{wish.status}</span></div>{wish.description && <p className="mt-2 text-sm text-muted">{wish.description}</p>}</div></div><form action={updateWishAdminMetaAction} className="mt-4 rounded-3xl border border-dashed border-brown/20 bg-brown p-4 text-white"><input type="hidden" name="wish_id" value={wish.id} /><div className="flex items-center gap-2"><EyeOff className="size-4 text-nailong" /><p className="text-xs font-bold text-nailong">只有管理员能看见</p></div><select name="status" className="field mt-3 text-brown" defaultValue={meta?.status ?? "not_started"}><option value="not_started">还没开始准备</option><option value="preparing">正在偷偷准备</option><option value="ready">已经准备好了</option></select><textarea name="secret_note" className="field mt-3 min-h-20 text-brown" maxLength={800} defaultValue={meta?.secret_note ?? ""} placeholder="秘密备注（她看不到）" /><SubmitButton className="mt-3" pendingText="保存秘密状态…">保存</SubmitButton></form>{wish.status !== "completed" && <form action={adminCompleteWishAction} className="mt-3"><input type="hidden" name="wish_id" value={wish.id} /><SubmitButton className="bg-green-100 text-green-800 shadow-none" pendingText="正在公开完成…">公开标记“愿望实现啦”</SubmitButton></form>}</Card>; }) : <Card className="py-14 text-center text-sm text-muted">她还没有写下愿望。</Card>}</div></div>;
}
