import { CalendarHeart, Trash2 } from "lucide-react";
import { deleteCalendarEventAction, saveCalendarEventAction } from "@/app/actions";
import { getCalendarData } from "@/lib/life-data";
import { dateInShanghai } from "@/lib/life";
import { Card } from "@/components/ui/card";
import { Flash } from "@/components/ui/flash";
import { SubmitButton } from "@/components/ui/submit-button";

export default async function AdminCalendarPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string }> }) {
  const [data, flash] = await Promise.all([getCalendarData(), searchParams]);
  return <div><div className="mb-5"><h2 className="text-xl font-black text-brown">纪念日管理</h2><p className="mt-1 text-sm text-muted">所有纪念日与普通用户的日历使用同一份数据。</p></div><Flash {...flash} /><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card><h3 className="font-black text-brown">添加纪念日</h3><form action={saveCalendarEventAction} className="mt-4 space-y-3"><input type="hidden" name="return_to" value="/admin/calendar" /><input name="title" className="field" required maxLength={80} placeholder="纪念日名称" /><input name="event_date" type="date" className="field" required defaultValue={dateInShanghai()} /><div className="grid grid-cols-2 gap-3"><select name="event_type" className="field"><option value="anniversary">纪念日</option><option value="birthday">生日</option><option value="travel">旅行</option><option value="special">特别事件</option></select><select name="repeat_type" className="field"><option value="none">不重复</option><option value="yearly">每年重复</option></select></div><textarea name="note" className="field min-h-20" maxLength={800} placeholder="备注（可选）" /><SubmitButton pendingText="正在保存…"><CalendarHeart className="size-4" />保存纪念日</SubmitButton></form></Card><div className="space-y-3">{data.events.length ? data.events.map((event) => <Card key={event.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-nailong-deep">{event.event_date} · {event.repeat_type === "yearly" ? "每年重复" : "仅一次"}</p><h3 className="mt-1 font-black text-brown">{event.title}</h3>{event.note && <p className="mt-1 text-sm text-muted">{event.note}</p>}</div><form action={deleteCalendarEventAction}><input type="hidden" name="event_id" value={event.id} /><input type="hidden" name="return_to" value="/admin/calendar" /><button className="flex size-10 items-center justify-center rounded-full bg-stone-100 text-muted" aria-label="删除"><Trash2 className="size-4" /></button></form></div></Card>) : <Card className="py-14 text-center text-sm text-muted">还没有纪念日。</Card>}</div></div></div>;
}
