import { MapPin, Plus, Trash2 } from "lucide-react";
import { deletePlaceAction, savePlaceAction } from "@/app/actions";
import { getPlacesData } from "@/lib/life-data";
import { formatDate } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { Flash } from "@/components/ui/flash";
import { MediaImage } from "@/components/ui/media-image";
import { SubmitButton } from "@/components/ui/submit-button";
import type { Place } from "@/types/database";

export const metadata = { title: "我们的足迹" };

function PlaceForm({ place }: { place?: Place }) {
  return <form action={savePlaceAction} className="space-y-3"><input type="hidden" name="id" value={place?.id ?? ""} /><input type="hidden" name="existing_image" value={place?.image_url ?? ""} /><input name="title" className="field" required maxLength={100} defaultValue={place?.title} placeholder="例如：第一次一起吃火锅" /><input name="place_name" className="field" required maxLength={120} defaultValue={place?.place_name} placeholder="地点名称" /><div className="grid grid-cols-2 gap-3"><input name="visit_date" type="date" className="field" required defaultValue={place?.visit_date} /><select name="place_type" className="field" defaultValue={place?.place_type ?? "date"}><option value="date">约会</option><option value="food">美食</option><option value="travel">旅行</option><option value="first">第一次</option><option value="other">其他</option></select></div><textarea name="description" className="field min-h-24" maxLength={1000} defaultValue={place?.description} placeholder="这里发生了什么？" /><label className="block text-xs font-semibold text-muted">照片（可选）<input name="image" type="file" accept="image/jpeg,image/png,image/webp" className="field mt-2 text-sm" /></label><details><summary className="cursor-pointer text-xs font-bold text-muted">可选：保存经纬度</summary><div className="mt-3 grid grid-cols-2 gap-3"><input name="latitude" type="number" step="0.000001" className="field" defaultValue={place?.latitude ?? ""} placeholder="纬度" /><input name="longitude" type="number" step="0.000001" className="field" defaultValue={place?.longitude ?? ""} placeholder="经度" /></div></details><SubmitButton pendingText="正在保存足迹…">保存足迹</SubmitButton></form>;
}

export default async function PlacesPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string }> }) {
  const [places, flash] = await Promise.all([getPlacesData(), searchParams]);
  return <main className="page-shell py-6 sm:py-10"><div className="mb-6"><p className="text-xs font-bold text-nailong-deep">OUR PLACES</p><h1 className="mt-1 text-3xl font-black text-brown">我们的足迹</h1><p className="mt-2 text-sm text-muted">先用地点卡片和时间轴收藏，以后接地图也不用重做数据。</p></div><Flash {...flash} />
    <div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><Card className="h-fit"><div className="mb-4 flex items-center gap-2"><Plus className="size-5 text-nailong-deep" /><h2 className="font-black text-brown">添加一个地方</h2></div><PlaceForm /></Card><div className="relative space-y-5 before:absolute before:bottom-8 before:left-5 before:top-8 before:w-px before:bg-amber-200">{places.length ? places.map((place) => <div key={place.id} className="relative pl-11"><span className="absolute left-1.5 top-7 z-10 flex size-7 items-center justify-center rounded-full bg-nailong text-brown ring-4 ring-cream"><MapPin className="size-4" /></span><Card><div className="grid gap-4 sm:grid-cols-[8rem_1fr]">{place.signed_url && <MediaImage src={place.signed_url} alt={place.title} className="aspect-square w-full rounded-2xl" />}<div><p className="text-xs font-bold text-nailong-deep">{formatDate(place.visit_date)} · {place.place_name}</p><h2 className="mt-1 text-lg font-black text-brown">{place.title}</h2>{place.description && <p className="mt-2 text-sm leading-6 text-muted">{place.description}</p>}{place.latitude !== null && place.longitude !== null && <p className="mt-2 text-xs text-muted">坐标 {place.latitude}, {place.longitude}</p>}</div></div><div className="mt-4 flex items-center gap-3"><details className="flex-1"><summary className="cursor-pointer text-sm font-bold text-nailong-deep">编辑足迹</summary><div className="mt-4 rounded-2xl bg-amber-50 p-4"><PlaceForm place={place} /></div></details><form action={deletePlaceAction}><input type="hidden" name="place_id" value={place.id} /><button className="flex size-10 items-center justify-center rounded-full bg-stone-100 text-muted" aria-label="删除足迹"><Trash2 className="size-4" /></button></form></div></Card></div>) : <Card className="py-16 text-center"><MapPin className="mx-auto size-10 text-nailong-deep" /><h2 className="mt-4 font-black text-brown">足迹时间轴还空空的</h2><p className="mt-2 text-sm text-muted">从第一次见面的地方开始记录吧。</p></Card>}</div></div>
  </main>;
}
