import Link from "next/link";
import { Gift, PackageCheck } from "lucide-react";
import { prepareMysteryOrderAction } from "@/app/actions";
import { getAdminMysteryData } from "@/lib/life-data";
import { formatDate } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { Flash } from "@/components/ui/flash";
import { StatusBadge } from "@/components/ui/status-badge";
import { SubmitButton } from "@/components/ui/submit-button";

export default async function AdminMysteriesPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string }> }) {
  const [data, flash] = await Promise.all([getAdminMysteryData(), searchParams]);
  return <div><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black text-brown">惊喜箱管理</h2><p className="mt-1 text-sm text-muted">真实内容与公开商品分表保存，准备好后再允许她揭晓。</p></div><Link href="/admin/products/new" className="pill-button"><Gift className="size-4" />创建惊喜箱</Link></div><Flash {...flash} />
    <section className="mb-7"><h3 className="mb-3 font-black text-brown">惊喜箱商品</h3><div className="grid gap-3 sm:grid-cols-2">{data.products.map((product) => { const detail = data.productDetails.find((item) => item.product_id === product.id); return <Card key={product.id} className="p-4"><div className="flex items-center justify-between gap-3"><h4 className="font-bold text-brown">{product.name}</h4><StatusBadge status={product.status} /></div><p className="mt-2 text-sm text-muted">公开：{product.mystery_hint}</p><p className="mt-2 rounded-2xl bg-brown p-3 text-xs text-white"><span className="font-bold text-nailong">真实惊喜：</span>{detail?.surprise_title ?? "尚未配置"}</p><Link href={`/admin/products/${product.id}`} className="mt-3 inline-block text-xs font-bold text-nailong-deep">编辑商品与秘密内容</Link></Card>; })}</div></section>
    <section><h3 className="mb-3 font-black text-brown">惊喜订单</h3><div className="space-y-4">{data.orders.length ? data.orders.map((order) => { const productDetail = data.productDetails.find((item) => item.product_id === order.product_id); const orderDetail = data.orderDetails.find((item) => item.order_id === order.id); return <Card key={order.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-muted">{formatDate(order.created_at, true)}</p><h4 className="mt-1 font-black text-brown">{order.product_name_snapshot}</h4></div><StatusBadge status={order.mystery_status ?? "preparing"} /></div>{order.mystery_status !== "revealed" ? <form action={prepareMysteryOrderAction} className="mt-4 rounded-3xl bg-amber-50 p-4"><input type="hidden" name="order_id" value={order.id} /><label className="block text-sm font-bold text-brown">惊喜名称<input name="surprise_title" className="field mt-2" required maxLength={100} defaultValue={orderDetail?.surprise_title ?? productDetail?.surprise_title ?? ""} /></label><label className="mt-3 block text-sm font-bold text-brown">真实内容<textarea name="surprise_content" className="field mt-2 min-h-24" required maxLength={1000} defaultValue={orderDetail?.surprise_content ?? productDetail?.surprise_content ?? ""} /></label><label className="mt-3 block text-sm font-bold text-brown">给她的留言<textarea name="admin_message" className="field mt-2 min-h-20" maxLength={800} defaultValue={orderDetail?.admin_message ?? ""} /></label><SubmitButton className="mt-3" pendingText="正在准备惊喜…"><PackageCheck className="size-4" />{order.mystery_status === "ready" ? "更新准备内容" : "标记为可以揭晓"}</SubmitButton></form> : <div className="mt-4 rounded-2xl bg-green-50 p-4 text-sm font-bold text-green-700">她已经揭晓：{orderDetail?.surprise_title}</div>}</Card>; }) : <Card className="py-14 text-center text-sm text-muted">还没有惊喜箱订单。</Card>}</div></section>
  </div>;
}
